all:
  children:
    shieldnet_servers:
      hosts:
        shieldnet_prod:
          ansible_host: 3.239.46.133
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/shieldnet-key.pem
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
