spring.application.name=shieldnet-benefits-api
server.port=8080

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

logging.level.com.shieldnet=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
