---
- name: Install Java 17
  yum:
    name: java-17-amazon-corretto
    state: present

- name: Verify Java installation
  command: java -version
  register: java_version

- name: Print Java version
  debug:
    msg: "Java version: {{ java_version.stderr }}"
